In [8]:
import os

os.environ["KERAS_BACKEND"] = "tensorflow"  # or "tensorflow" or "torch"

import keras_nlp
import keras

# Use mixed precision to speed up all training in this guide.
keras.mixed_precision.set_global_policy("float32")

In [9]:
BATCH_SIZE = 16
imdb_train = keras.utils.text_dataset_from_directory(
    "feed001_tech_only/train",
    batch_size=BATCH_SIZE,
)

Found 209 files belonging to 10 classes.


In [10]:
imdb_test = keras.utils.text_dataset_from_directory(
    "feed001_tech_only/test",
    batch_size=BATCH_SIZE,
)

Found 209 files belonging to 10 classes.


In [4]:
# Inspect first review
# Format is (review text tensor, label tensor)
print(imdb_train.unbatch().take(1).get_single_element())

(<tf.Tensor: shape=(), dtype=string, numpy=b'DE-EN-LANG-SWITCH-NO-TRANSLATION\r\nDE-EN-LANG-SWITCH-NO-TRANSLATION\r\nDE-EN-LANG-SWITCH-NO-TRANSLATION\r\nDE-EN-LANG-SWITCH-NO-TRANSLATION\r\n&FUNCTIONALITY&\r\nThe function module MRM_DISTRIBUTION_BNK distributes unplanned delivery\r\ncosts among the items in an invoice. The unplanned delivery costs are\r\nstored in field "BNKAN_FW". The system only takes into account items\r\nthat meet the following conditions:\r\nThe item is allocated to the invoice\r\nThe item concerned is not a planned delivery costs item such as customs\r\nduty or freight costs\r\nThe item is relevant for unplanned delivery costs\r\nParameters:\r\nImport parameters:\r\nI_BEZNK: Unplanned delivery costs\r\nI_BUKRS: Company code\r\nI_BUDAT: Posting date (of the invoice document)\r\nI_WAERS: Currency key (in the invoice)\r\nI_XRECH: Indicator: post invoice\r\nI_UMRECHNEN: Indicates whether conversion to local currency is\r\nnecessary\r\nCharacteristic = SPACE (Default):

In [11]:
classifier = keras_nlp.models.BertClassifier.from_preset("bert_tiny_en_uncased_sst2")

In [6]:
classifier.predict(["I love modular workflows in keras-nlp!"])

2024-02-21 09:28:45.761822: I external/local_xla/xla/service/service.cc:168] XLA service 0x7fe48c0953b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-02-21 09:28:45.761852: I external/local_xla/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2024-02-21 09:28:45.786448: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.


1/1 [==============================] - 1s 1s/step


I0000 00:00:1708504126.052913    3390 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2024-02-21 09:28:46.053947: E external/local_xla/xla/stream_executor/stream_executor_internal.h:177] SetPriority unimplemented for this stream.


array([[-1.5387032,  1.5418267]], dtype=float32)

In [7]:
classifier.predict(["determine the receipt quantity still available for a particular material"])

1/1 [==============================] - 0s 338ms/step


array([[0.04323041, 0.09722595]], dtype=float32)

In [12]:
classifier.evaluate(imdb_test)

14/14 [==============================] - 2s 95ms/step - loss: nan - sparse_categorical_accuracy: 0.0957


[nan, 0.09569378197193146]